// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.2
// - protoc             v3.21.12
// source: nft_transfer/v1/nft_transfer.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNftTransferGetNftTransfer = "/api.nft_transfer.v1.NftTransfer/GetNftTransfer"

type NftTransferHTTPServer interface {
	GetNftTransfer(context.Context, *GetNftTransferRequest) (*GetNftTransferReply, error)
}

func RegisterNftTransferHTTPServer(s *http.Server, srv NftTransferHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/nfttransfer/getnfttransfer", _NftTransfer_GetNftTransfer0_HTTP_Handler(srv))
}

func _NftTransfer_GetNftTransfer0_HTTP_Handler(srv NftTransferHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNftTransferRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNftTransferGetNftTransfer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNftTransfer(ctx, req.(*GetNftTransferRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetNftTransferReply)
		return ctx.Result(200, reply)
	}
}

type NftTransferHTTPClient interface {
	GetNftTransfer(ctx context.Context, req *GetNftTransferRequest, opts ...http.CallOption) (rsp *GetNftTransferReply, err error)
}

type NftTransferHTTPClientImpl struct {
	cc *http.Client
}

func NewNftTransferHTTPClient(client *http.Client) NftTransferHTTPClient {
	return &NftTransferHTTPClientImpl{client}
}

func (c *NftTransferHTTPClientImpl) GetNftTransfer(ctx context.Context, in *GetNftTransferRequest, opts ...http.CallOption) (*GetNftTransferReply, error) {
	var out GetNftTransferReply
	pattern := "/v1/nfttransfer/getnfttransfer"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNftTransferGetNftTransfer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
