server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    host: gateway.aws-us-east-1.bytehouse.cloud:19000
    region: US-EAST-1
    account: AWSCOPZD
    user: ksam
    password: P@55word
    dbname: data_warehouse
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
